move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
     j1_joint:
      has_acceleration_limits: true
      max_acceleration:  103.3639398087
      has_deceleration_limits: true
      max_deceleration: -103.3639398087
     j2_joint:
      has_acceleration_limits: true
      max_acceleration:  291.216665200164
      has_deceleration_limits: true
      max_deceleration: -251.668723012488
     j3_joint:
      has_acceleration_limits: true
      max_acceleration:  29.00390625
      has_deceleration_limits: true
      max_deceleration: -29.00390625
     j4_joint:
      has_acceleration_limits: true
      max_acceleration:  558.225196091509
      has_deceleration_limits: true
      max_deceleration: -558.225196091509
