move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
     j1_joint:
      has_acceleration_limits: true
      max_acceleration:  67.4112650926307
      has_deceleration_limits: true
      max_deceleration: -67.4112650926307
     j2_joint:
      has_acceleration_limits: true
      max_acceleration:  215.716048296418
      has_deceleration_limits: true
      max_deceleration: -215.716048296418
     j3_joint:
      has_acceleration_limits: true
      max_acceleration:  21.97265625
      has_deceleration_limits: true
      max_deceleration: -26.3671875
     j4_joint:
      has_acceleration_limits: true
      max_acceleration:  558.225196091509
      has_deceleration_limits: true
      max_deceleration: -558.225196091509
