move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
     j1_joint:
      has_acceleration_limits: true
      max_acceleration:  67.41126509263071
      has_deceleration_limits: true
      max_deceleration: -67.41126509263071
     j2_joint:
      has_acceleration_limits: true
      max_acceleration:  215.7160482964183
      has_deceleration_limits: true
      max_deceleration: -215.7160482964183
     j3_joint:
      has_acceleration_limits: true
      max_acceleration:  21.97265625
      has_deceleration_limits: true
      max_deceleration: -26.3671875
     j4_joint:
      has_acceleration_limits: true
      max_acceleration:  558.2251960915091
      has_deceleration_limits: true
      max_deceleration: -558.2251960915091
