epson_moveit_except_demo:
  ros__parameters:
    planning_pipelines:
      pipeline_names: ["ompl"]

    plan_request_params:
      planning_attempts: 10
      planning_pipeline: ompl
      max_velocity_scaling_factor: 1.0
      max_acceleration_scaling_factor: 1.0
